### ISSUE TITLE
Sprint 1 - Reaching for the High/Low Basket (Kailyn & Hasini)

### ISSUE THREAD

**Issue by Walker21122008** [sta-titansrobotics/27294-IntoTheDeep#11]
** - October 8, 2024**
We finished two sets of the linear motion slider and checked how long they would extend. For one set of arms, we are using four linear sliders, which extend more than the higher basket, which is good. 
- We still have to connect the 2 separate sliders and connect them using surgical tubing. We also believe that we can attach the gear to the robot like the V2 class bot which would make the arm turn instead of making it go upright only. If it is slanted throughout the robot, it would help to make it fit within the frame. 
https://www.youtube.com/watch?v=AxRqJGVuRSE
- This video showcases the method that we are going to be using for now to ensure that the arm doesn't require the turning part.

**Comment by kailyn-s** [comment]
**October 8 - Assembled Two Sets of Linear Motion Sliders**

<img width="558" alt="Screenshot 2024-10-08 at 4 37 58 PM" src="https://github.com/user-attachments/assets/dbb4e693-9f6a-4c34-a066-7634fdd59366">
<img width="994" alt="Screenshot 2024-10-08 at 4 38 09 PM" src="https://github.com/user-attachments/assets/a7aebdcd-7fd3-4600-847a-5a18102f3e35">
<img width="555" alt="Screenshot 2024-10-08 at 4 38 21 PM" src="https://github.com/user-attachments/assets/c7c21c3f-e37d-4f37-9fce-2ad696dd95ec">


**Issues**:
- one of the sliders is stiff and needs to be loosened in order to achieve a smooth reach

**Comment by kailyn-s** [comment]
**October 9, 2024 - Kailyn & Hasini**

Today we began with finishing off the motion sliders as well as attempting to connect them. By connecting them, we were able to reach a length that stretched from the ground to above the high basket, leaving more than enough room for our output method. We also added the pulleys which will further contribute to the function of the arm later on. Tomorrow we plan to begin building a second version of this model to give support to the output component Thomas is constructing.

**Issues**
- The sliders are still a bit stiff and tends to get stuck at certain points when extending due to impurities in the extrusions which is an issue we plan to address tomorrow

**Comment by kailyn-s** [comment]
**October 9, 2024 - Combining the Linear Motion Sliders**
<img width="506" alt="Screenshot 2024-10-09 at 9 49 04 PM" src="https://github.com/user-attachments/assets/7dd61e12-8b6b-496d-a82d-5b48f7d170de">
<img width="501" alt="Screenshot 2024-10-09 at 9 49 18 PM" src="https://github.com/user-attachments/assets/f4897921-2a2e-4606-884f-70ec0768ae4d">

**Comment by kailyn-s** [comment]
**October 10, 2024 Kailyn & Hasini**

Today we began with the base of the arm and utilizing the pulleys to produce the base motion of the sliders. As seen in the photos below, we threaded a string through the various pulleys to connect all the pieces together. By pulling on one end of the string, we are able to see how the arm can be extended to the height of the high basket.  This method would be proven effective and more efficient.

**Issues:**

- we lack the proper gear to attach the string to the motor
- the string tends to fall out of the pulleys
- We need to position the motor properly to line up with the pulleys and make sure that the string doesn't get lose

**Comment by kailyn-s** [comment]
**October 10 - Stringing through the Pulleys**
<img width="494" alt="Screenshot 2024-10-10 at 8 19 33 PM" src="https://github.com/user-attachments/assets/8f3fee80-f806-4c9d-87e6-9a68ab5e34ca">
<img width="472" alt="Screenshot 2024-10-10 at 8 19 46 PM" src="https://github.com/user-attachments/assets/0fce404b-ac8c-42c5-bc92-10e15ef96037">

**Comment by Walker21122008** [comment]
**October 15, 2024 - Hasini and Kailyn**
Today, we were starting to make the second set of arms. so far we have 2 linear extenders and we are making fast progress now since we know the steps to build it.
- Mr. Fabroa gave us an idea for how we can use the pulley system since the pulley kit from the Go Bilda kit from the other team would be too small

**Issues:**
- We are still figuring out how to mount the motor.
- We have to figure out how to make the linear slides slide back down easily rather than getting stuck.

**Comment by kailyn-s** [comment]
**October 15 - Creating a Second Linear Motion System**
<img width="580" alt="Screenshot 2024-10-15 at 9 38 07 PM" src="https://github.com/user-attachments/assets/9883d1ed-f5d7-4ebe-9d33-1d2c702e8f94">
